lock_cars:
    pattern:  /cars/{bbdd}/{num}
    defaults: { _controller: ImportBundle:Import:importLockCars, bbdd: 'old_cars', num: 0 }

incidences:
    pattern:  /incidences/{bbdd}/{num}
    defaults: { _controller: ImportBundle:Import:importLockIncidences, bbdd: 'incidences', num: 0 }

import:
    pattern:  /{bbdd}/{num}
    defaults: { _controller: ImportBundle:Import:import, bbdd: null, num: 0 }
