lock:
    pattern:  /lock/{bbdd}/{num}
    defaults: { _controller: ImportBundle:Import:importLock, bbdd: null, num: 0 }

import:
    pattern:  /{bbdd}/{num}
    defaults: { _controller: ImportBundle:Import:import, bbdd: null, num: 0 }