lock_cars:
    path:  /cars/{bbdd}/{num}
    defaults: { _controller: ImportBundle:Import:importLockCars, bbdd: 'old_cars', num: 0 }

incidences:
    path:  /incidences/{bbdd}/{num}
    defaults: { _controller: ImportBundle:Import:importLockIncidences, bbdd: 'incidences', num: 0 }

test_mail:
    path:  /mail
    defaults: { _controller: ImportBundle:Import:testMailing }

user_credentials:
    path:  /user-credentials/{type}
    defaults: { _controller: ImportBundle:Import:sendUserCredentials }

import_workshop_fr:
    path:  /importWorkshopFR
    defaults: { _controller: ImportBundle:Import:importWorkshopFR }

import:
    path:  /{bbdd}/{num}
    defaults: { _controller: ImportBundle:Import:import, bbdd: null, num: 0 }