################################
#   APDO. GESTIÓN DE TICKETS   #
################################

formTicket:
    pattern:  /ticket
    defaults: { _controller: TicketingBundle:Ticketing:form }
#
#formTicketPickModelJSON:
#    pattern: /ticket/pickModel/{make}
#    defaults: { _controller: TicketingBundle:Ticketing:getModels }
#
#formTicketPickVersionJSON:
#    pattern: /ticket/pickVersion/{model}
#    defaults: { _controller: TicketingBundle:Ticketing:getVersions }
#    
#formTicketPickSubsystemJSON:
#    pattern: /ticket/pickSubsys/{sys}
#    defaults: { _controller: TicketingBundle:Ticketing:getSubsys }    
#    
##########################
#   GESTIÓN DE TICKETS   #
##########################



# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

# app/config/routing.yml
#fos_js_routing:
#    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"