##############################
#   APDO. RUTAS PARTNER      #
##############################
partner_list:
    pattern:  /list/{page}/{option}
    defaults: { _controller: PartnerBundle:Default:list, page: 1 , option: null }

partner_edit:
    pattern: /edit/{id}
    defaults: { _controller: PartnerBundle:Default:editPartner }

partner_delete:
    pattern: /delete/{id}
    defaults: { _controller: PartnerBundle:Default:deletePartner }

partner_new:
    pattern: /new
    defaults: { _controller: PartnerBundle:Default:newPartner }

##############################
#       RUTAS AJAX           #
##############################
user_provinces:
    pattern: /provincesFromRegion
    defaults: { _controller: UtilBundle:Default:provincesFromRegion }