##############################
#   APDO. RUTAS PARTNER      #
##############################
partner_list:
    pattern:  /partner/list/{page}/{country}/{partner}
    defaults: { _controller: PartnerBundle:Partner:list, page: 1 , country: 'none', partner: 'none' }

partner_new:
    pattern: /new/partner
    defaults: { _controller: PartnerBundle:Partner:newPartner }

partner_edit:
    pattern: /edit/partner/{id}
    defaults: { _controller: PartnerBundle:Partner:editPartner }

partner_delete:
    pattern: /delete/partner/{id}
    defaults: { _controller: PartnerBundle:Partner:deletePartner }


##############################
#   APDO. RUTAS SHOP         #
##############################
shop_list:
    pattern:  /shop/list/{page}/{country}
    defaults: { _controller: PartnerBundle:Shop:list, page: 1 , country: 'none' }

shop_new:
    pattern: /new/shop
    defaults: { _controller: PartnerBundle:Shop:newShop }

shop_edit:
    pattern: /edit/shop/{id}
    defaults: { _controller: PartnerBundle:Shop:editShop }

shop_delete:
    pattern: /delete/shop/{id}
    defaults: { _controller: PartnerBundle:Shop:deleteShop }
