##############################
#   APDO. RUTAS ORDER        #
##############################

list_orders:
    path: /orders/list/{page}/{option}/{country}/{w_idpartner}/{w_id}/{partner}/{status}/{term}/{field}
    defaults: { _controller: OrderBundle:Order:listOrders, page: 1 ,option: 'workshop_pending' ,w_idpartner: '0', w_id: '0', country: '0', partner: '0', status: '0', term: '0', field: '0'  } 
    options:
        expose: true

##############################
#   APDO. RUTAS SHOP ORDER   #
##############################
shopOrder_listShops:
    path: /shop/listShops/{page}/{partner}
    defaults: { _controller: OrderBundle:ShopOrder:listShops, page: 1 , partner: 'none' }
    options:
        expose: true

shopOrder_new:
    path: /shop/new
    defaults: { _controller: OrderBundle:ShopOrder:new }

shopOrder_edit:
    path: /shop/edit/{id}
    defaults: { _controller: OrderBundle:ShopOrder:edit }

shopOrder_change_status:
    path: /shop/change_status/{id}/{status}
    defaults: { _controller: OrderBundle:ShopOrder:changeStatus }

shopOrder_remove:
    path: /shop/remove/{id}
    defaults: { _controller: OrderBundle:ShopOrder:remove }

shopOrder_delete:
    path: /shop/delete/{id}
    defaults: { _controller: OrderBundle:ShopOrder:delete }

# shopOrder_list_orders:
#     path: /shop/list/listWorkshopOrders
#     defaults: { _controller: OrderBundle:ShopOrder:listWorkshopOrders }

shopOrder_accept:
    path: /shop/accept/{id}/{status}
    defaults: { _controller: OrderBundle:ShopOrder:accept }

shopOrder_resendOrder:
    path: /shop/resend/{id}/
    defaults: { _controller: OrderBundle:ShopOrder:resendOrder }

shopOrder_reject:
    path: /shop/reject/{id}
    defaults: { _controller: OrderBundle:ShopOrder:reject }


###################################
#   APDO. RUTAS WORKSHOPORDER     #
###################################

workshopOrder_listWorkshops:
    path: /workshop/listWorkshops/{page}/{w_idpartner}/{w_id}/{country}/{partner}/{status}/{term}/{field}
    defaults: { _controller: OrderBundle:WorkshopOrder:listWorkshops, page: 1 , w_idpartner: '0', w_id: '0', country: '0', partner: '0', status: '0', term: '0', field: '0'  }
    options:
        expose: true

workshopOrder_new:
    path: /workshop/new
    defaults: { _controller: OrderBundle:WorkshopOrder:new }

workshopOrder_edit:
    path: /workshop/edit/{id}
    defaults: { _controller: OrderBundle:WorkshopOrder:edit }

workshopOrder_change_status:
    path: /workshop/change_status/{id}/{status}
    defaults: { _controller: OrderBundle:WorkshopOrder:changeStatus }

workshopOrder_remove:
    path: /workshop/remove/{id}
    defaults: { _controller: OrderBundle:WorkshopOrder:remove }

workshopOrder_accept:
    path: /workshop/accept/{id}/{status}
    defaults: { _controller: OrderBundle:WorkshopOrder:accept }

workshopOrder_resendOrder:
    path: /workshop/resend/{id}/
    defaults: { _controller: OrderBundle:WorkshopOrder:resend }

workshopOrder_reject:
    path: /workshop/reject/{id}
    defaults: { _controller: OrderBundle:WorkshopOrder:reject }

doPdfWorkshop:
    path: /workshop/doPdfWorkshop/{id}
    defaults: { _controller: OrderBundle:WorkshopOrder:doPdfWorkshop }


##############################
#       RUTAS AJAX           #
##############################

search_cif:
    path: /new/{cif}
    defaults: { _controller: OrderBundle:WorkshopOrder:findCif }
    options:
        expose: true