##############################
#   APDO. RUTAS SHOP ORDER   #
##############################

list_orders:
    pattern: /orders/list
    defaults: { _controller: OrderBundle:Order:listOrders}

##############################
#   APDO. RUTAS SHOP ORDER   #
##############################
shopOrder_listShops:
    pattern: /shop/listShops
    defaults: { _controller: OrderBundle:ShopOrder:listShops}

shopOrder_new:
    pattern: /shop/new
    defaults: { _controller: OrderBundle:ShopOrder:new }

shopOrder_edit:
    pattern: /shop/edit/{id}
    defaults: { _controller: OrderBundle:ShopOrder:edit }

shopOrder_change_status:
    pattern: /shop/change_status/{id}/{status}
    defaults: { _controller: OrderBundle:ShopOrder:changeStatus }

shopOrder_remove:
    pattern: /shop/remove/{id}
    defaults: { _controller: OrderBundle:ShopOrder:remove }

shopOrder_delete:
    pattern: /shop/delete/{id}
    defaults: { _controller: OrderBundle:ShopOrder:delete }

# shopOrder_list_orders:
#     pattern: /shop/list/listWorkshopOrders
#     defaults: { _controller: OrderBundle:ShopOrder:listWorkshopOrders }

shopOrder_accept:
    pattern: /shop/accept/{id}/{status}
    defaults: { _controller: OrderBundle:ShopOrder:accept }

# shopOrder_resendOrder:
#     pattern: /shop/resend/{id}/
#     defaults: { _controller: OrderBundle:ShopOrder:resend }

shopOrder_reject:
    pattern: /shop/reject/{id}
    defaults: { _controller: OrderBundle:ShopOrder:reject }


###################################
#   APDO. RUTAS WORKSHOPORDER     #
###################################

workshopOrder_listWorkshops:
    pattern: /workshop/listWorkshops
    defaults: { _controller: OrderBundle:WorkshopOrder:listWorkshops }

workshopOrder_new:
    pattern: /workshop/new
    defaults: { _controller: OrderBundle:WorkshopOrder:new }

workshopOrder_edit:
    pattern: /workshop/edit/{id}
    defaults: { _controller: OrderBundle:WorkshopOrder:edit }

workshopOrder_change_status:
    pattern: /workshop/change_status/{id}/{status}
    defaults: { _controller: OrderBundle:WorkshopOrder:changeStatus }

workshopOrder_remove:
    pattern: /workshop/remove/{id}
    defaults: { _controller: OrderBundle:WorkshopOrder:remove }

workshopOrder_accept:
    pattern: /workshop/accept/{id}/{status}
    defaults: { _controller: OrderBundle:WorkshopOrder:accept }

workshopOrder_resendOrder:
    pattern: /workshop/resend/{id}/
    defaults: { _controller: OrderBundle:WorkshopOrder:resend }

workshopOrder_reject:
    pattern: /workshop/reject/{id}
    defaults: { _controller: OrderBundle:WorkshopOrder:reject }