<?php
namespace Adservice\PartnerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends EntityRepository
{
    public function findByWorkshop($id_workshop)
    {
        $partners = $this->findAll();
        foreach ($partners as $partner) {

            $workshops = $partner->getWorkshops();
            foreach ($workshops as $workshop) {

                if($workshop->getId() == $id_workshop){
                    return array($partner);
                }
            }
        }
    }
}