##############################
#   APDO. RUTAS WORKSHOP     #
##############################
workshop_list:
    pattern:  /list
    defaults: { _controller: WorkshopBundle:Default:list }
    
workshop_edit:
    pattern: /edit/{id}
    defaults: { _controller: WorkshopBundle:Default:editWorkshop }

workshop_delete:
    pattern: /delete/{id}
    defaults: { _controller: WorkshopBundle:Default:deleteWorkshop }

workshop_new:
    pattern: /new
    defaults: { _controller: WorkshopBundle:Default:newWorkshop }

new_workshop_order:
    pattern: /newWorkshopOrder
    defaults: { _controller: WorkshopBundle:Default:newWorkshopOrder }

active_workshop_order:
    pattern: /activeWorkshopOrder
    defaults: { _controller: WorkshopBundle:Default:activeWorkshopOrder }
    
order_list_workshop:
    pattern: /listWorkshopOrder
    defaults: { _controller: WorkshopBundle:Default:listWorkshopOrder }
    
register_workshop:
    pattern: /registerWorkshopOrder/{id}/{action}
    defaults: { _controller: WorkshopBundle:Default:registerWorkshopOrder }

change_status_workshop:
    pattern: /changeStatusWorkshopOrder/{id}/{action}
    defaults: { _controller: WorkshopBundle:Default:changeStatusWorkshopOrder }
    

##############################
#       RUTAS AJAX           #
##############################
user_provinces: 
    pattern: /provincesFromRegion
    defaults: { _controller: UtilBundle:Default:provincesFromRegion }