##############################
#   APDO. RUTAS WORKSHOP     #
##############################
workshop_list:
    path:  /list/{page}/{w_idpartner}/{w_id}/{country}/{catserv}/{partner}/{status}/{term}/{field}
    defaults: { _controller: WorkshopBundle:Workshop:list, page: 1 , w_idpartner: '0', w_id: '0', country: '0', catserv: '0', partner: '0', status: '0', term: '0', field: '0'  }
    options:
        expose: true

workshop_edit:
    path: /edit/{id}
    defaults: { _controller: WorkshopBundle:Workshop:editWorkshop }

workshop_delete:
    path: /delete/{id}
    defaults: { _controller: WorkshopBundle:Workshop:deleteWorkshop }

workshop_new:
    path: /new
    defaults: { _controller: WorkshopBundle:Workshop:newWorkshop }

workshop_observation:
    path: /observation/{id}/{id_ticket}
    defaults: { _controller: WorkshopBundle:Workshop:workshopObservation }

workshop_activate_deactivate:
    path: /activateDeactive/{workshop_id}
    defaults: { _controller: WorkshopBundle:Workshop:deactivateActivateWorkshop, workshop_id: 0 }

workshop_deactivate_observation:
    path: /deactivateObservation/{workshop_id}
    defaults: { _controller: WorkshopBundle:Workshop:workshopDeactivateObservation, workshop_id: 0 }

##############################
#   APDO. RUTAS DIAGNOSIS    #
##############################
diagnosis_machine_list:
    path:  /diag_list/{page}/{country}/{catserv}
    defaults: { _controller: WorkshopBundle:DiagnosisMachine:listDiagnosisMachine, page: 1 , country: 'none', catserv: 0   }
    options:
        expose: true

diagnosis_machine_edit:
    path: /diag_edit/{id}
    defaults: { _controller: WorkshopBundle:DiagnosisMachine:editDiagnosisMachine, id: null }

# diagnosis_machine_new:
#     path: /diag_new
#     defaults: { _controller: WorkshopBundle:DiagnosisMachine:newDiagnosisMachine }

##############################
#   APDO. RUTAS TYPOLOGY     #
##############################
typology_list:
    path:  /typo_list/{page}/{country}/{catserv}
    defaults: { _controller: WorkshopBundle:Typology:listTypology, page: 1, country: 'none', catserv: 0  }
    options:
        expose: true

typology_edit:
    path: /typo_edit/{id}
    defaults: { _controller: WorkshopBundle:Typology:editTypology, id: null }

# tipology_new:
#     path: /typo_new
#     defaults: { _controller: WorkshopBundle:Typology:newTypology }

##############################
#       RUTAS AJAX           #
##############################
#user_provinces:
#    path: /provincesFromRegion
#    defaults: { _controller: UtilBundle:Workshop:provincesFromRegion }

search_cif:
    path: /new/{cif}
    defaults: { _controller: WorkshopBundle:Workshop:findCif }
    options:
        expose: true
