##############################
#   APDO. RUTAS WORKSHOP     #
##############################
workshop_list:
    pattern:  /list/{page}/{country}
    defaults: { _controller: WorkshopBundle:Workshop:list, page: 1 , country: 'none'  }

workshop_edit:
    pattern: /edit/{id}
    defaults: { _controller: WorkshopBundle:Workshop:editWorkshop }

workshop_delete:
    pattern: /delete/{id}
    defaults: { _controller: WorkshopBundle:Workshop:deleteWorkshop }

workshop_new:
    pattern: /new
    defaults: { _controller: WorkshopBundle:Workshop:newWorkshop }

##############################
#   APDO. RUTAS DIAGNOSIS    #
##############################
diagnosis_machine_list:
    pattern:  /diag_list/{page}/{country}
    defaults: { _controller: WorkshopBundle:DiagnosisMachine:listDiagnosisMachine, page: 1 , country: 'none'  }

diagnosis_machine_edit:
    pattern: /diag_edit/{id}
    defaults: { _controller: WorkshopBundle:DiagnosisMachine:editDiagnosisMachine, id: null }

# diagnosis_machine_new:
#     pattern: /diag_new
#     defaults: { _controller: WorkshopBundle:DiagnosisMachine:newDiagnosisMachine }

##############################
#   APDO. RUTAS TYPOLOGY     #
##############################
typology_list:
    pattern:  /typo_list/{page}/{country}
    defaults: { _controller: WorkshopBundle:Typology:listTypology, page: 1 , country: 'none'  }

typology_edit:
    pattern: /typo_edit/{id}
    defaults: { _controller: WorkshopBundle:Typology:editTypology, id: null }

# tipology_new:
#     pattern: /typo_new
#     defaults: { _controller: WorkshopBundle:Typology:newTypology }

##############################
#       RUTAS AJAX           #
##############################
#user_provinces:
#    pattern: /provincesFromRegion
#    defaults: { _controller: UtilBundle:Workshop:provincesFromRegion }