##############################
#   APDO. RUTAS WORKSHOP     #
##############################
workshop_list:
    pattern:  /list/{page}/{w_idpartner}/{w_id}/{country}/{partner}/{status}/{term}/{field}
    defaults: { _controller: WorkshopBundle:Workshop:list, page: 1 , w_idpartner: '0', w_id: '0', country: '0', partner: '0', status: '0', term: '0', field: '0'  }
    options:
        expose: true

workshop_edit:
    pattern: /edit/{id}
    defaults: { _controller: WorkshopBundle:Workshop:editWorkshop }

workshop_delete:
    pattern: /delete/{id}
    defaults: { _controller: WorkshopBundle:Workshop:deleteWorkshop }

workshop_new:
    pattern: /new
    defaults: { _controller: WorkshopBundle:Workshop:newWorkshop }

workshop_observation:
    pattern: /observation/{id}/{id_ticket}
    defaults: { _controller: WorkshopBundle:Workshop:workshopObservation }

##############################
#   APDO. RUTAS DIAGNOSIS    #
##############################
diagnosis_machine_list:
    pattern:  /diag_list/{page}/{country}
    defaults: { _controller: WorkshopBundle:DiagnosisMachine:listDiagnosisMachine, page: 1 , country: 'none'  }
    options:
        expose: true

diagnosis_machine_edit:
    pattern: /diag_edit/{id}
    defaults: { _controller: WorkshopBundle:DiagnosisMachine:editDiagnosisMachine, id: null }

# diagnosis_machine_new:
#     pattern: /diag_new
#     defaults: { _controller: WorkshopBundle:DiagnosisMachine:newDiagnosisMachine }

##############################
#   APDO. RUTAS TYPOLOGY     #
##############################
typology_list:
    pattern:  /typo_list/{page}/{country}
    defaults: { _controller: WorkshopBundle:Typology:listTypology, page: 1 , country: 'none'  }
    options:
        expose: true

typology_edit:
    pattern: /typo_edit/{id}
    defaults: { _controller: WorkshopBundle:Typology:editTypology, id: null }

# tipology_new:
#     pattern: /typo_new
#     defaults: { _controller: WorkshopBundle:Typology:newTypology }

##############################
#       RUTAS AJAX           #
##############################
#user_provinces:
#    pattern: /provincesFromRegion
#    defaults: { _controller: UtilBundle:Workshop:provincesFromRegion }