##############################
#   APDO. RUTAS WORKSHOP     #
##############################
workshop_list:
    pattern:  /list/{page}/{option}
    defaults: { _controller: WorkshopBundle:Default:list, page: 1 , option: null  }

workshop_edit:
    pattern: /edit/{id}
    defaults: { _controller: WorkshopBundle:Default:editWorkshop }

workshop_delete:
    pattern: /delete/{id}
    defaults: { _controller: WorkshopBundle:Default:deleteWorkshop }

workshop_new:
    pattern: /new
    defaults: { _controller: WorkshopBundle:Default:newWorkshop }

###################################
#   APDO. RUTAS WORKSHOPORDER     #
###################################
#new_workshop_order:
#    pattern: /newWorkshopOrder
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:newWorkshopOrder }
#
#active_workshop_order:
#    pattern: /activeWorkshopOrder
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:activeWorkshopOrder }
#
#order_list_workshop:
#    pattern: /listWorkshopOrder
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:listWorkshopOrder }
#
#register_workshop:
#    pattern: /registerWorkshopOrder/{id}/{action}
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:registerWorkshopOrder }
#
#change_status_workshop:
#    pattern: /changeStatusWorkshopOrder/{id}/{action}
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:changeStatusWorkshopOrder }



workshopOrder_workshoplist:
    pattern: /listWorkshopsWorkshopOrder
    defaults: { _controller: WorkshopBundle:WorkshopOrder:listWorkshops}

workshopOrder_createNewOrder:
    pattern: /newCreateWorkshopOrder
    defaults: { _controller: WorkshopBundle:WorkshopOrder:newCreateWorkshopOrder }

workshopOrder_createModifyOrder:
    pattern: /newModifyWorkshopOrder/{id}
    defaults: { _controller: WorkshopBundle:WorkshopOrder:newModifyWorkshopOrder }

workshopOrder_createChangeStatusOrder:
    pattern: /changeStatusOrder/{id}/{status}
    defaults: { _controller: WorkshopBundle:WorkshopOrder:newChangeStatusOrder }

workshopOrder_removeWorkshopOrder:
    pattern: /removeWorkshopOrder/{id}
    defaults: { _controller: WorkshopBundle:WorkshopOrder:removeWorkshopOrder }

workshopOrder_listWorkshopOrders:
    pattern: /listWorkshopOrders
    defaults: { _controller: WorkshopBundle:WorkshopOrder:listWorkshopOrders }

workshopOrder_changeStatusOrder:
    pattern: /listWorkshopOrders/{id}/{status}
    defaults: { _controller: WorkshopBundle:WorkshopOrder:doActionWorkshop }

workshopOrder_resendOrder:
    pattern: /resendOrder/{id}/{status}
    defaults: { _controller: WorkshopBundle:WorkshopOrder:resendOrder }

workshopOrder_setReasonRejectionOrder:
    pattern: /setReasonRejectionOrder/{id}
    defaults: { _controller: WorkshopBundle:WorkshopOrder:setReasonRejectionOrder }

#workshopOrder_new:
#    pattern: /newWorkshopOrder/{id}/{action}
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:newWorkshopOrder }
#
#workshopOrder_edit:
#    pattern: /editWorkshopOrder/{id}/{action}
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:editWorkshopOrder }
#
#workshopOrder_list:
#    pattern: /listWorkshopOrder
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:listWorkshopOrder }
#
#workshopOrder_workshoplist:
#    pattern: /workshoplistWorkshopOrder
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:listWorkshops}
#
#workshopOrder_change_status:
#    pattern: /changeWorkshopStatusOrder/{id}/{status}
#    defaults: { _controller: WorkshopBundle:WorkshopOrder:changeWorkshopStatusOrder}




##############################
#       RUTAS AJAX           #
##############################
user_provinces:
    pattern: /provincesFromRegion
    defaults: { _controller: UtilBundle:Default:provincesFromRegion }