parameters:
#    workshop.example.class: Adservice\WorkshopBundle\Example

services:
#    workshop.example:
#        class: %workshop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    validadorCIF:
        class: Adservice\UtilBundle\Entity\ValidadorCIF
        arguments: [cif]
