################################
#   GESTIÓN DE TICKETS         #
################################

newTicket:
    pattern:  /ticket/new/
    defaults: { _controller: TicketBundle:Ticket:newTicket }
 
editTicket:
    pattern:  /ticket/edit/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:editTicket } 
    
findTicket:
    pattern:  /ticket/find/
    defaults: { _controller: TicketBundle:Ticket:findTicket } 
    
showTicket:
    pattern:  /ticket/show/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:showTicket }
    
listTicket:
    pattern:  /ticket/
    defaults: { _controller: TicketBundle:Ticket:listTicket }

ticketWorkshopList:
    pattern:  /ticket/workshopList/
    defaults: { _controller: TicketBundle:Ticket:workshopList }    

ticketsFromWorkshop:
    pattern:  /ticket/getTicketsFromWorkshop/{id_workshop}
    defaults: { _controller: TicketBundle:Ticket:getTicketsFromWorkshop }

assignTicket:
    pattern: /ticket/assingTicket/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:assignTicketSelectUser }
    
assignUserToTicket:
    pattern:  /ticket/assign/{id_ticket}/
    defaults: { _controller: TicketBundle:Ticket:assignUserToTicket }

# Ajax    
fill_tickets:
    pattern:  /ticket/ajax
    defaults: { _controller: TicketBundle:Ticket:fill_tickets }
    
################################
#    GESTIÓN DE POSTS          #
################################  

showPost:
    pattern:  /ticket/posts/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:showPost }
      
################################
#    GESTIÓN DE INCIDENCIAS    #
################################        
        
newIncidence:
    pattern:  /incidence/new/
    defaults: { _controller: TicketBundle:Incidence:newIncidence }
    
createIncidence:
    pattern:  /incidence/create/{id_ticket}
    defaults: { _controller: TicketBundle:Incidence:createIncidence }

editIncidence:
    pattern:  /incidence/edit/{id_incidence}
    defaults: { _controller: TicketBundle:Incidence:editIncidence } 
    
showIncidence:
    pattern:  /incidence/show/{id_incidence}
    defaults: { _controller: TicketBundle:Incidence:showIncidence }    
    
listIncidence:
    pattern:  /incidence/
    defaults: { _controller: TicketBundle:Incidence:listIncidence }

# Ajax    
fill_incidences:
    pattern:  /incidence/ajax
    defaults: { _controller: TicketBundle:Incidence:fill_incidences }
    
    