################################
#   GESTIÓN DE TICKETS         #
################################

newTicket:
    pattern:  /ticket/new/{id_workshop}
    defaults: { _controller: TicketBundle:Ticket:newTicket, id_workshop: null }

editTicket:
    pattern:  /ticket/edit/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:editTicket }

deleteTicket:
    pattern:  /ticket/delete/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:deleteTicket }

findTicket:
    pattern:  /ticket/find/
    defaults: { _controller: TicketBundle:Ticket:findTicket }

showTicket:
    pattern:  /ticket/show/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:showTicket }

listTicketFiltered:
    pattern:  /ticket/filtered/{page}/{id_workshop}/{id_ticket}/{status}/
    defaults: { _controller: TicketBundle:Ticket:listTicketFiltered, page: 1, id_workshop: 'none', id_ticket: 'none', status: 'all' }

ticketWorkshopList:
    pattern:  /ticket/workshopList/{page}/
    defaults: { _controller: TicketBundle:Ticket:workshopList, page: 1 }

ticketsFromWorkshop:
    pattern:  /ticket/getTicketsFromWorkshop/{id_workshop}/{page}/
    defaults: { _controller: TicketBundle:Ticket:getTicketsFromWorkshop, page: 1 }

assignTicket:
    pattern: /ticket/assingTicket/{id_ticket}/
    defaults: { _controller: TicketBundle:Ticket:assignTicketSelectUser }

assignUserToTicket:
    pattern:  /ticket/assign/{id_ticket}/
    defaults: { _controller: TicketBundle:Ticket:assignUserToTicket }

blockTicket:
    pattern: /ticket/assingAssesor/{id_ticket}/{id_user}
    defaults: { _controller: TicketBundle:Ticket:blockTicket, id_user: null }

closeTicket:
    pattern:  /ticket/close/{id_ticket}/
    defaults: { _controller: TicketBundle:Ticket:closeTicket, id_ticket: null }

reopenTicket:
    pattern: /ticket/reopen/{id_ticket}/
    defaults: { _controller: TicketBundle:Ticket:reopenTicket }

listTicket:
    pattern:  /ticket/{page}/{option}
    defaults: { _controller: TicketBundle:Ticket:listTicket, page: 1 , option: null  }


################################
#    GESTIÓN DE POSTS          #
################################

showPost:
    pattern:  /ticket/posts/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:showPost }