################################
#   GESTIÓN DE TICKETS         #
################################

newTicket:
    pattern:  /ticket/new/{id_workshop}
    defaults: { _controller: TicketBundle:Ticket:newTicket, id_workshop: null }

editTicket:
    pattern:  /ticket/edit/{id}
    defaults: { _controller: TicketBundle:Ticket:editTicket }

deleteTicket:
    pattern:  /ticket/delete/{id}
    defaults: { _controller: TicketBundle:Ticket:deleteTicket }

findTicket:
    pattern:  /ticket/find/
    defaults: { _controller: TicketBundle:Ticket:findTicket }

showTicket:
    pattern:  /ticket/show/{id}
    defaults: { _controller: TicketBundle:Ticket:showTicket }

findTicketById:
    pattern:  /ticket/findTicketById/
    defaults: { _controller: TicketBundle:Ticket:findTicketById }

findTicketByBMV:
    pattern:  /ticket/findTicketByBMV/{page}/{brand}/{model}/{version}/{num_rows}
    defaults: { _controller: TicketBundle:Ticket:findTicketByBMV, page: 1, brand: 0, model: 0, version: 0, num_rows: 10 }
    options:
        expose: true

# listTicketFiltered:
#     pattern:  /ticket/filtered/{page}/{id_workshop}/{id_ticket}/{status}/
#     defaults: { _controller: TicketBundle:Ticket:listTicketFiltered, page: 1, id_workshop: 'none', id_ticket: 'none', status: 'all' }

ticketWorkshopList:
    pattern:  /ticket/workshopList/{page}/
    defaults: { _controller: TicketBundle:Ticket:workshopList, page: 1 }

ticketsFromWorkshop:
    pattern:  /ticket/getTicketsFromWorkshop/{id_workshop}/{page}/
    defaults: { _controller: TicketBundle:Ticket:getTicketsFromWorkshop, page: 1 }

assignTicket:
    pattern: /ticket/assingTicket/{id}/
    defaults: { _controller: TicketBundle:Ticket:assignTicketSelectUser }

assignUserToTicket:
    pattern:  /ticket/assign/{id}/
    defaults: { _controller: TicketBundle:Ticket:assignUserToTicket }

blockTicket:
    pattern: /ticket/assingAssesor/{id}/{id_user}
    defaults: { _controller: TicketBundle:Ticket:blockTicket, id_user: null }

closeTicket:
    pattern:  /ticket/close/{id}
    defaults: { _controller: TicketBundle:Ticket:closeTicket, id: null }

reopenTicket:
    pattern: /ticket/reopen/{id}/
    defaults: { _controller: TicketBundle:Ticket:reopenTicket }

listTicket:
    pattern:  /ticket/{page}/{num_rows}/{country}/{option}
    defaults: { _controller: TicketBundle:Ticket:listTicket, page: 1 , num_rows: 10 , country: 0, option: null  }


################################
#    GESTIÓN DE POSTS          #
################################

showPost:
    pattern:  /ticket/posts/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:showPost }

post_edit:
    pattern:  /ticket/edit_post/{id}/
    defaults: { _controller: TicketBundle:Ticket:editPost, id: null }

##############################
#   APDO. RUTAS SENTENCE     #
##############################
sentence_list:
    pattern:  /sentence_list/{page}/{country}
    defaults: { _controller: TicketBundle:Sentence:listSentence, page: 1 , country: 'none'  }
    options:
        expose: true

sentence_edit:
    pattern: /sentence_edit/{id}
    defaults: { _controller: TicketBundle:Sentence:editSentence, id: null }