################################
#   GESTIÓN DE TICKETS         #
################################

newTicket:
    pattern:  /ticket/new/{id_workshop}
    defaults: { _controller: TicketBundle:Ticket:newTicket, id_workshop: null }

editTicket:
    pattern:  /ticket/edit/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:editTicket }

deleteTicket:
    pattern:  /ticket/delete/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:deleteTicket }

findTicket:
    pattern:  /ticket/find/
    defaults: { _controller: TicketBundle:Ticket:findTicket }

showTicket:
    pattern:  /ticket/show/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:showTicket }

listTicket:
    pattern:  /ticket/
    defaults: { _controller: TicketBundle:Ticket:listTicket }

listTicketFiltered:
    pattern:  /ticket/filtered
    defaults: { _controller: TicketBundle:Ticket:listTicketFiltered }

ticketWorkshopList:
    pattern:  /ticket/workshopList/
    defaults: { _controller: TicketBundle:Ticket:workshopList }

ticketsFromWorkshop:
    pattern:  /ticket/getTicketsFromWorkshop/{id_workshop}
    defaults: { _controller: TicketBundle:Ticket:getTicketsFromWorkshop }

assignTicket:
    pattern: /ticket/assingTicket/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:assignTicketSelectUser }

assignUserToTicket:
    pattern:  /ticket/assign/{id_ticket}/
    defaults: { _controller: TicketBundle:Ticket:assignUserToTicket }

blockTicket:
    pattern: /ticket/assingAssesor/{id_ticket}/{id_user}
    defaults: { _controller: TicketBundle:Ticket:blockTicket, id_user: null }

closeTicket:
    pattern:  /ticket/close/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:closeTicket }


################################
#    GESTIÓN DE POSTS          #
################################

showPost:
    pattern:  /ticket/posts/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:showPost }

###########################
#   APDO. AJAX            #
###########################

fill_tickets:
    pattern:  /ticket/ajax
    defaults: { _controller: TicketBundle:Ticket:fill_tickets }

ticket_system:
    pattern: /ticketSystem
    defaults: { _controller: TicketBundle:Default:ticketSystem }

tbl_system:
    pattern: /tblSystem
    defaults: { _controller: TicketBundle:Default:tblSystem }
