################################
#   GESTIÓN DE TICKETS         #
################################

newTicket:
    path:  /ticket/new/{id_workshop}/{einatech}/{reset}
    defaults: { _controller: TicketBundle:Ticket:newTicket, id_workshop: null, einatech: 0, reset: 0 }
editTicket:
    path:  /ticket/edit/{id}
    defaults: { _controller: TicketBundle:Ticket:editTicket }

deleteTicket:
    path:  /ticket/delete/{id}
    defaults: { _controller: TicketBundle:Ticket:deleteTicket }

findTicket:
    path:  /ticket/find/
    defaults: { _controller: TicketBundle:Ticket:findTicket }

showTicket:
    path:  /ticket/show/{id}
    defaults: { _controller: TicketBundle:Ticket:showTicket }
    options:
        expose: true

findTicketById:
    path:  /ticket/findTicketById/
    defaults: { _controller: TicketBundle:Ticket:findTicketById }

findTicketByIdAndWorkshop:
    path:  /ticket/findTicketByIdAndWorkshop/
    defaults: { _controller: TicketBundle:Ticket:findTicketByIdAndWorkshop }

findTicketByBMV:
    path:  /ticket/findTicketByBMV/{page}/{brand}/{model}/{version}/{system}/{subsystem}/{num_rows}
    defaults: { _controller: TicketBundle:Ticket:findTicketByBMV, page: 1, brand: 0, model: 0, version: 0, system: 0, subsystem: 0, num_rows: 10 }
    options:
        expose: true

findAssessorTicketByBMV:
    path:  /ticket/findAssessorTicketByBMV/{page}
    defaults: { _controller: TicketBundle:Ticket:findAssessorTicketByBMV, page: null }
    options:
        expose: true

insert_cif:
    path:  /insertcif/{workshop_id}
    defaults: { _controller: WorkshopBundle:Workshop:insertCif, workshop_id: 0 , country: '0'}

# listTicketFiltered:
#     path:  /ticket/filtered/{page}/{id_workshop}/{id_ticket}/{status}/
#     defaults: { _controller: TicketBundle:Ticket:listTicketFiltered, page: 1, id_workshop: 'none', id_ticket: 'none', status: 'all' }

ticketWorkshopList:
    path:  /ticket/workshopList/{page}/
    defaults: { _controller: TicketBundle:Ticket:workshopList, page: 1 }

ticketsFromWorkshop:
    path:  /ticket/getTicketsFromWorkshop/{id_workshop}/{page}/
    defaults: { _controller: TicketBundle:Ticket:getTicketsFromWorkshop, page: 1 }

assignTicket:
    path: /ticket/assignTicket/{id}/
    defaults: { _controller: TicketBundle:Ticket:assignTicketSelectUser }

assignUserToTicket:
    path:  /ticket/assign/{id}/
    defaults: { _controller: TicketBundle:Ticket:assignUserToTicket }

blockTicket:
    path: /ticket/assignAssesor/{id}/{id_user}
    defaults: { _controller: TicketBundle:Ticket:blockTicket, id_user: null }

closeTicket:
    path:  /ticket/close/{id}/{close}
    defaults: { _controller: TicketBundle:Ticket:closeTicket, id: null, close: '1' }

editDescription:
    path:  /ticket/editDescription/{id}
    defaults: { _controller: TicketBundle:Ticket:editDescription, id: null }

reopenTicket:
    path: /ticket/reopen/{id}/
    defaults: { _controller: TicketBundle:Ticket:reopenTicket }

listTicket:
    path:  /ticket/{page}/{num_rows}/{country}/{lang}/{catserv}/{option}/{workshop_id}/{adviser_id}
    defaults: { _controller: TicketBundle:Ticket:listTicket, page: 1, num_rows: 10, country: 0, lang: 0, catserv: 0, option: null, workshop_id: null, adviser_id: null  }

callTicket:
    path:  /call/{code_partner}/{code_workshop}
    defaults: { _controller: TicketBundle:Ticket:callTicket, code_partner: 0 , code_workshop: 0 }

listMotors:
    path:  /engines/
    defaults: { _controller: TicketBundle:Ticket:listMotors  }

################################
#    GESTIÓN DE POSTS          #
################################

showPost:
    path:  /ticket/posts/{id_ticket}
    defaults: { _controller: TicketBundle:Ticket:showPost }

post_edit:
    path:  /ticket/edit_post/{id}/
    defaults: { _controller: TicketBundle:Ticket:editPost, id: null }

##############################
#   APDO. RUTAS SENTENCE     #
##############################
sentence_list:
    path:  /sentence_list/{page}/{country}
    defaults: { _controller: TicketBundle:Sentence:listSentence, page: 1 , country: 'none'  }
    options:
        expose: true

sentence_edit:
    path: /sentence_edit/{id}
    defaults: { _controller: TicketBundle:Sentence:editSentence, id: null }