parameters:
#    ticketing.example.class: Adservice\TicketingBundle\Example

services:
#    ticketing.example:
#        class: %ticketing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]