parameters:
#    ticket.example.class: Adservice\TicketBundle\Example

services:
    cms.mailer:
        class: Adservice\UtilBundle\Entity\Mailer
        arguments: ["@mailer","@swiftmailer.transport.real","@templating"]

    instant_mailer:
        class: "%swiftmailer.class%"
        arguments: ["@?swiftmailer.transport.real"]

    car.helper:
            class: Adservice\CarBundle\Service\CarHelper
            arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage", "@templating"]