parameters:
#    ticket.example.class: Adservice\TicketBundle\Example

services:
#    ticket.example:
#        class: %ticket.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
