listStatistics:
    pattern:  /list/{type}/{page}/{date_from}/{date_to}/{partner}/{status}/{country}
    defaults: { _controller: StatisticBundle:Statistic:list, type: null, page: 1, date_from: 'none', date_to: 'none', partner: 'none', status: 'none', country: 'none' }

doExcel:
    pattern:  /doExcel/{type}/{page}/{date_from}/{date_to}/{partner}/{status}/{country}
    defaults: { _controller: StatisticBundle:Statistic:doExcel, type: null, page: 1, date_from: 'none', date_to: 'none', partner: 'none', status: 'none', country: 'none' }
