listStatistics:
    pattern:  /list/{type}/{page}/{from_y}/{from_m}/{from_d}/{to_y}/{to_m}/{to_d}/{partner}/{status}/{country}
    defaults: { _controller: StatisticBundle:Statistic:list, type: '0', page: 1, from_y: '0', from_m: '0', from_d: '0', to_y: '0', to_m: '0', to_d: '0', partner: '0', status: '0', country: '0' }
    options:
        expose: true
doExcel:
    pattern:  /doExcel/{type}/{page}/{from_y}/{from_m}/{from_d}/{to_y}/{to_m}/{to_d}/{partner}/{status}/{country}
    defaults: { _controller: StatisticBundle:Statistic:doExcel, type: '0', page: 1, from_y: '0', from_m: '0', from_d: '0', to_y: '0', to_m: '0', to_d: '0', partner: 'none', status: 'none', country: 'none' }
    options:
        expose: true
