# DEFAULT
changeLang:
    path:  /changeLang/{locale}
    defaults: { _controller: AppBundle:Default:changeLang, locale: locale }
#    options:
#        expose: true

index:
    path:  /
    defaults: { _controller: AppBundle:Default:index }

# HELP
help:
    path:  /help
    defaults: { _controller: AppBundle:Default:help }

# LOGIN
login:
    path:  /login
    defaults: { _controller: AppBundle:Security:login }
autologin:
    path:  /autologin
    defaults: { _controller: AppBundle:Security:autologin }


# USER
selectRole:
    path:  /users/select-role
    defaults: { _controller: AppBundle:User:selectRole }

userNew:
    path:  /users/user-new/{role_id}/{id}
    defaults: { _controller: AppBundle:User:userNew, id: null, role_id: null }

userEdit:
    path:  /users/user-edit/{role_id}/{id}
    defaults: { _controller: AppBundle:User:userEdit, id: null, role_id: null }

userDelete:
    path:  /users/user-delete/{role_id}/{id}
    defaults: { _controller: AppBundle:User:userDelete, id: null, role_id: null }

userView:
    path:  /users/user-view/{role_id}/{id}
    defaults: { _controller: AppBundle:User:userView, id: null, role_id: null }

searchId:
    path:  /users/search-id/{role_id}/{id}
    defaults: { _controller: AppBundle:User:searchId, id: null, role_id: null }

users:
    path:  /users/{role_id}/{page}/{filter}/{value}
    defaults: { _controller: AppBundle:User:users, role_id: null, page: 1, filter: 0, value: 0 }

# TICKET
tickets:
    path:  /tickets
    defaults: { _controller: AppBundle:Ticket:tickets }
