
# PARTNER
getMaxCodePartner:
    path:  /getMaxCodePartner
    defaults: { _controller: AppBundle:Ajax:getMaxCodePartner }
    options:
        expose: true

# WORKSHOP
getMaxCodeWorkshopByPartner:
    path:  /getMaxCodeWorkshopByPartner/{partner}
    defaults: { _controller: AppBundle:Ajax:getMaxCodeWorkshopByPartner, partner: partner }
    options:
        expose: true
    