parameters:
#    partner.example.class: Adservice\PartnerBundle\Example

services:
#    partner.example:
#        class: %partner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
