imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        route_logo: '%route_logo%'
        route_logo_mail: '%route_logo_mail%'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            db_old:
                driver:   %database_old_driver%
                host:     %database_old_host%
                port:     %database_old_port%
                dbname:   %database_old_name%
                user:     %database_old_user%
                password: %database_old_password%
                charset:  UTF8
            db_lock:
                driver:   %database_lock_driver%
                host:     %database_lock_host%
                port:     %database_lock_port%
                dbname:   %database_lock_name%
                user:     %database_lock_user%
                password: %database_lock_password%
                charset:  UTF8

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection:   default
                mappings:
                    UserBundle: ~
                    UtilBundle: ~
                    PartnerBundle: ~
                    WorkshopBundle: ~
                    TicketBundle: ~
                    CarBundle: ~
                    PopupBundle: ~
                    OrderBundle: ~
                    StatisticBundle: ~
                # auto_mapping: true
            em_old:
                connection:   db_old
                mappings:
                    ImportBundle: ~
                # auto_mapping: true
            em_lock:
                connection:   db_lock
                mappings:
                    LockBundle: ~
                # auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
        # auto_mapping: true

        # ORIGINAL #
        # auto_generate_proxy_classes: %kernel.debug%
        # auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
        type:                 file
        path:                 "%kernel.root_dir%/spool"
jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }

parameters:
    adservice.post.uploadpath: 'web/uploads/tickets'

knp_snappy:
    pdf:
        enabled:    true
        binary:     "/usr/local/bin/wkhtmltopdf"
        options:    []