OrderBundle:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/order

StatisticBundle:
    resource: "@StatisticBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/statistic

CarBundle:
    resource: "@CarBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

PopupBundle:
    resource: "@PopupBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/popup

WorkshopBundle:
    resource: "@WorkshopBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/workshop

PartnerBundle:
    resource: "@PartnerBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/partner

TicketBundle:
    resource: "@TicketBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

UtilBundle:
    resource: "@UtilBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

_login:
    pattern:  /
    defaults: { _controller: UserBundle:Login:goToLogin }

#redirect:
#    pattern: /{_locale}/{_location}/
#    defaults:
#         _controller: FrameworkBundle:Redirect:urlRedirect
#         path: /{_locale}/{_location}/
#         permanent: true