UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

TicketBundle:
    resource: "@TicketBundle/Resources/config/routing.yml"
    prefix:   /

UtilBundle:
    resource: "@UtilBundle/Resources/config/routing.yml"
    prefix:   /
