WorkshopBundle:
    resource: "@WorkshopBundle/Resources/config/routing.yml"
    prefix:   /workshop

PartnerBundle:
    resource: "@PartnerBundle/Resources/config/routing.yml"
    prefix:   /partner

TicketBundle:
    resource: "@TicketBundle/Resources/config/routing.yml"
    prefix:   /

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

UtilBundle:
    resource: "@UtilBundle/Resources/config/routing.yml"
    prefix:   /
