
############################################################################
# LINEA PARA IMPORTAR DATOS DE LA BBDD: COMENTAR UNA VEZ EN PROD           #
############################################################################
#ImportBundle:
#    resource: "@ImportBundle/Resources/config/routing.yml"
#    prefix:   /{_locale}/import/
############################################################################

autologin:
    path: /autologin/
    defaults: { _controller: UtilBundle:Security:autologin }

LockBundle:
    resource: "@LockBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/lock/
    requirements:
          _locale: "%locale_routing%"

OrderBundle:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/order
    requirements:
          _locale: "%locale_routing%"

StatisticBundle:
    resource: "@StatisticBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/statistic
    requirements:
          _locale: "%locale_routing%"

CarBundle:
    resource: "@CarBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
          _locale: "%locale_routing%"

PopupBundle:
    resource: "@PopupBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/popup
    requirements:
          _locale: "%locale_routing%"

WorkshopBundle:
    resource: "@WorkshopBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/workshop
    requirements:
          _locale: "%locale_routing%"

PartnerBundle:
    resource: "@PartnerBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/partner
    requirements:
          _locale: "%locale_routing%"

TicketBundle:
    resource: "@TicketBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
          _locale: "%locale_routing%"

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
          _locale: "%locale_routing%"

UtilBundle:
    resource: "@UtilBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
          _locale: "%locale_routing%"

_login:
    path:  /
    defaults: { _controller: UserBundle:Login:goToLogin }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#redirect:
#    path: /{_locale}/{_location}/
#    defaults:
#         _controller: FrameworkBundle:Redirect:urlRedirect
#         path: /{_locale}/{_location}/
#         permanent: true