app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: "config/routing_api.yml"
    prefix: /{_locale}/api
    requirements:
        _locale: en|fr|es|pt
