app:
    resource: "config/routing.yml"
    prefix:   /{_locale}

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

default:
    path:  /
    defaults: { _controller: AppBundle:Default:index  }

logout:
    path:   /logout