app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: "@ApiBundle/Controller/ApiController.php"
    type: rest
    prefix: /{_locale}/api
    requirements:
        _locale: en|fr|es|pt
    # resource: "config/routing_api.yml"
