StatisticBundle:
    resource: "@StatisticBundle/Resources/config/routing.yml"
    prefix:   /

SystemBundle:
    resource: "@SystemBundle/Resources/config/routing.yml"
    prefix:   /

CarBundle:
    resource: "@CarBundle/Resources/config/routing.yml"
    prefix:   /
PopupBundle:
    resource: "@PopupBundle/Resources/config/routing.yml"
    prefix:   /popup

WorkshopBundle:
    resource: "@WorkshopBundle/Resources/config/routing.yml"
    prefix:   /workshop

PartnerBundle:
    resource: "@PartnerBundle/Resources/config/routing.yml"
    prefix:   /partner

TicketBundle:
    resource: "@TicketBundle/Resources/config/routing.yml"
    prefix:   /

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

UtilBundle:
    resource: "@UtilBundle/Resources/config/routing.yml"
    prefix:   /
