security:

    firewalls:
        main:
            pattern: /.*
            anonymous: true
#            provider: user_db
            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: user_index
                always_use_default_target_path: true
            logout:
                path: user_logout
                target: user_login
            security: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    providers:
        usuarios:
            entity: { class: Adservice\UserBundle\Entity\User, property: username }

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_ASSESSOR, ROLE_USER, ROLE_TOP_AD]
        ROLE_ASSESSOR: ROLE_USER
        ROLE_TOP_AD: ROLE_SUPER_AD
        ROLE_SUPER_AD: ROLE_AD
        ROLE_AD: ROLE_COMMERCIAL

    access_control:
      - { path: ^/(es|en|fr|pt|pl|nl)/user/login,                 roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/help,                       roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/privacy,                    roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/partner/shop,               roles: [ROLE_AD], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/partner,                    roles: [ROLE_TOP_AD], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/shop,                       roles: [ROLE_ADMIN, ROLE_AD], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/order,                      roles: [ROLE_ADMIN, ROLE_COMMERCIAL], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/user/list,                  roles: [ROLE_ADMIN], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/user,                       roles: [ROLE_USER, ROLE_AD, ROLE_COMMERCIAL], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/popup,                      roles: [ROLE_USER, ROLE_AD], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/workshop/observation,       roles: [ROLE_ASSESSOR], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/workshop,                   roles: [ROLE_ADMIN, ROLE_AD], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/ticket/workshopList,        roles: [ROLE_ASSESSOR], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/ticket/assingAssesor,       roles: [ROLE_ASSESSOR], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/ticket/close,               roles: [ROLE_USER], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/ticket,                     roles: [ROLE_USER], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/car,                        roles: [ROLE_ASSESSOR], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/statistic/list-top,         roles: [ROLE_AD], requires_channel: https }
      - { path: ^/(es|en|fr|pt|pl|nl)/statistic,                  roles: [ROLE_AD], requires_channel: https }
      # - { path: ^/(es|en|fr|pt|pl|nl)/lock,                     roles: [ROLE_USER]                  }
      - { path: ^/(es|en|fr|pt|pl|nl)/import,                     roles: [ROLE_SUPER_ADMIN], requires_channel: https }
      # - { path: ^/(es|en|fr|pt|pl|nl)/,                         roles: [ROLE_USER]                  }
      - { path: ^/,                                         roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    encoders:
        Adservice\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
