security:

    firewalls:
        main:
            pattern: /.*
            anonymous: true
#            provider: user_db
            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: user_index
                always_use_default_target_path: true
            logout:
                path: user_logout
                target: user_login
            security: true
            remember_me:
                key:      "%secret%"
                lifetime: 604800
                path:     ^/
                domain:   ~

    providers:
        usuarios:
            entity: { class: Adservice\UserBundle\Entity\User, property: username }

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_ASSESSOR, ROLE_USER, ROLE_AD]
        ROLE_ASSESSOR: ROLE_USER
        ROLE_SUPER_AD: ROLE_AD

    access_control:
      - { path: ^/(es|en|fr)/user/login,                 roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/(es|en|fr)/partner/shop,               roles: [ROLE_AD]                    }
      - { path: ^/(es|en|fr)/partner,                    roles: [ROLE_ADMIN]                 }
      - { path: ^/(es|en|fr)/shop,                       roles: [ROLE_ADMIN, ROLE_AD]        }
      - { path: ^/(es|en|fr)/user/list,                  roles: [ROLE_ADMIN]                 }
      - { path: ^/(es|en|fr)/user,                       roles: [ROLE_USER, ROLE_AD]         }
      - { path: ^/(es|en|fr)/popup,                      roles: [ROLE_USER]                  }
      - { path: ^/(es|en|fr)/workshop,                   roles: [ROLE_ADMIN, ROLE_AD]        }
      - { path: ^/(es|en|fr)/ticket/workshopList,        roles: [ROLE_ADMIN]                 }
      - { path: ^/(es|en|fr)/ticket/assingAssesor,       roles: [ROLE_ASSESSOR]              }
      - { path: ^/(es|en|fr)/ticket/close,               roles: [ROLE_ASSESSOR]              }
      - { path: ^/(es|en|fr)/ticket,                     roles: [ROLE_USER]                  }
      - { path: ^/(es|en|fr)/car,                        roles: [ROLE_USER]                  }
      - { path: ^/(es|en|fr)/statistic,                  roles: [ROLE_ADMIN]                 }
      # - { path: ^/(es|en|fr)/lock,                     roles: [ROLE_USER]                  }
      - { path: ^/(es|en|fr)/import,                     roles: [ROLE_SUPER_ADMIN]           }

    encoders:
        Adservice\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
