security:

    firewalls:
        main:
            pattern: /.*
            anonymous: true
#            provider: user_db
            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: user_index
                always_use_default_target_path: true
            logout:
                path: user_logout
                target: user_login
            security: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    providers:
        usuarios:
            entity: { class: Adservice\UserBundle\Entity\User, property: username }

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_ASSESSOR, ROLE_USER, ROLE_TOP_AD]
        ROLE_ASSESSOR: ROLE_USER
        ROLE_TOP_AD: ROLE_SUPER_AD
        ROLE_SUPER_AD: ROLE_AD

    access_control:
      - { path: ^/,                                         roles: IS_AUTHENTICATED_ANONYMOUSLY,  requires_channel: https }
      - { path: ^/(es|en|fr|pt)/autologin,                  roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/(es|en|fr|pt)/user/login,                 roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/(es|en|fr|pt)/help,                       roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/(es|en|fr|pt)/privacy,                    roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/(es|en|fr|pt)/partner/shop,               roles: [ROLE_AD]                    }
      - { path: ^/(es|en|fr|pt)/partner,                    roles: [ROLE_ADMIN]                 }
      - { path: ^/(es|en|fr|pt)/shop,                       roles: [ROLE_ADMIN, ROLE_AD]        }
      - { path: ^/(es|en|fr|pt)/order,                      roles: [ROLE_ADMIN, ROLE_AD]        }
      - { path: ^/(es|en|fr|pt)/user/list,                  roles: [ROLE_ADMIN]                 }
      - { path: ^/(es|en|fr|pt)/user,                       roles: [ROLE_USER, ROLE_AD]         }
      - { path: ^/(es|en|fr|pt)/popup,                      roles: [ROLE_USER, ROLE_AD]         }
      - { path: ^/(es|en|fr|pt)/workshop/observation,       roles: [ROLE_ASSESSOR]              }
      - { path: ^/(es|en|fr|pt)/workshop,                   roles: [ROLE_ADMIN, ROLE_AD]        }
      - { path: ^/(es|en|fr|pt)/ticket/workshopList,        roles: [ROLE_ASSESSOR]              }
      - { path: ^/(es|en|fr|pt)/ticket/assingAssesor,       roles: [ROLE_ASSESSOR]              }
      - { path: ^/(es|en|fr|pt)/ticket/close,               roles: [ROLE_USER]                  }
      - { path: ^/(es|en|fr|pt)/ticket,                     roles: [ROLE_USER]                  }
      - { path: ^/(es|en|fr|pt)/car,                        roles: [ROLE_USER]                  }
      - { path: ^/(es|en|fr|pt)/statistic/list-top,         roles: [ROLE_TOP_AD]                }
      - { path: ^/(es|en|fr|pt)/statistic,                  roles: [ROLE_TOP_AD]                }
      # - { path: ^/(es|en|fr|pt)/lock,                     roles: [ROLE_USER]                  }
      - { path: ^/(es|en|fr|pt)/import,                     roles: [ROLE_SUPER_ADMIN]           }
      # - { path: ^/(es|en|fr|pt)/,                         roles: [ROLE_USER]                  }

    encoders:
        Adservice\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
