security:
    
    firewalls:
        main:
            pattern: /.*
            anonymous: true
#            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /profile
                always_use_default_target_path: true
            logout:
                path: logout
                target: /
            security: true
            remember_me:
                key:      "%secret%"
                lifetime: 604800
                path:     ^/
                domain:   ~ 

    providers:
        usuarios:
            entity: { class: Adservice\UsuarioBundle\Entity\Usuario, property: nombre }
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }

    encoders: 
        Adservice\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }










################
### ALEX B #####
################

#security:
#    session_fixation_strategy: migrate
#  
#    encoders:
#        Adservice\TicketingBundle\Entity\User:
#            algorithm: sha512
#            encode-as-base64: true
#            iterations: 10
#    
#    role_hierarchy:
#        ROLE_ADMIN: [ROLE_USER]
#
#    providers:
#        user_db:
#            entity: { class: Adservice\TicketingBundle\Entity\User, property: username }
#
#    firewalls:
#        main:
#            pattern: /.* 
#            # ESTO ERA LO QUE FALLABA
#            #pattern: ^/(.)/.* 
#            provider: user_db
#            form_login:
#                login_path: /login
#                check_path: /login_check
#                always_use_default_target_path: true
#                default_target_path: /loadUser
#            logout:
#                path: /logout
#                target: /
#                #invalidate_session: false
#            security: true
#            anonymous: true
#            remember_me:
#                key:      "%secret%"
#                lifetime: 604800
#                path:     ^/
#                domain:   ~ 
#
#    access_control:
#      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#      - { path: ^/lang/(.), roles: IS_AUTHENTICATED_ANONYMOUSLY }
#      - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }






#security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    providers:
#        in_memory:
#            users:
#                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#
#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: /demo/secured/login_check
#                login_path: /demo/secured/login
#            logout:
#                path:   /demo/secured/logout
#                target: /demo/
#            #anonymous: ~
#            #http_basic:
#            #    realm: "Secured Demo Area"
#
#    access_control:
#        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
