# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
        user_provider:
            entity:
                class: AppBundle:User
                property: token


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Api firewall, will take care of all /api/* requests via the authenticator
        api:
            pattern: ^/(es|en|fr)/api/*
            security: true
            # Need anonymus acces for the /public part of the API. If not given,
            # authentication required message will show (which is not correct for
            #/api/public requests)
            anonymous: ~
            guard:
                authenticators:
                    - app.token_authenticator

        main:
            anonymous: ~
            logout: ~

            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
