# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            # algorithm: sha512
            # encode_as_base64: false
            # iterations: 10

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        users:
            entity:
                class: AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: users
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: index
            logout:
                path:   /logout
                target: /
                invalidate_session: false

                # csrf_token_generator: security.csrf.token_manager
                # You can change the name of the field by setting csrf_parameter and change the token ID by setting csrf_token_id in your configuration:
                # csrf_parameter: _csrf_security_token
                # csrf_token_id: a_private_string
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    role_hierarchy:
        ROLE_GOD:           ROLE_SUPER_ADMIN
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
        ROLE_ADMIN:         [ ROLE_ADVISOR, ROLE_TOP ]
        ROLE_TOP:           ROLE_SUPER_PARTNER
        ROLE_SUPER_PARTNER: ROLE_PARTNER
        ROLE_PARTNER:       ROLE_COMMERCIAL
        ROLE_COMMERCIAL:    ROLE_USER
        ROLE_ADVISOR:       ROLE_WORKSHOP
        ROLE_WORKSHOP:      ROLE_USER

    access_control:
      - { path: ^/(es|en|fr|pt)/login,                      roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/(es|en|fr|pt)/changeLang,                 roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/(es|en|fr|pt)/help,                       roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/(es|en|fr|pt)/user,                       roles: ROLE_PARTNER  }
      - { path: ^/(es|en|fr|pt)/ticket,                     roles: ROLE_WORKSHOP }
      - { path: ^/(es|en|fr|pt),                            roles: ROLE_USER }
