# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
    utils:
        class: AppBundle\Utils\Utils
    slugger:
        class: AppBundle\Utils\Slugger
    locale:
        class: AppBundle\Utils\Locale
    export:
        class: AppBundle\Utils\Export
    ticket:
        class: AppBundle\Utils\Ticket
    user:
        class: AppBundle\Utils\User
        
