#############################
#   APDO. RUTAS GENÉRICAS   #
#############################
popup_list:
    pattern: /list/{page}/{country}
    defaults: { _controller: PopupBundle:Popup:popupList, page: 1 , country: 'none'  }
    options:
        expose: true

popup_edit:
    pattern: /edit/{id}
    defaults: { _controller: PopupBundle:Popup:editPopup }

popup_delete:
    pattern: /delete/{id}
    defaults: { _controller: PopupBundle:Popup:deletePopup }

popup_new:
    pattern: /new
    defaults: { _controller: PopupBundle:Popup:newPopup }

###########################
#   APDO. AJAX   #
###########################
popup_get:
    pattern:  /get
    defaults: { _controller: PopupBundle:Popup:getPopup }
    options:
        expose: true
