#############################
#   APDO. RUTAS GENÉRICAS   #
#############################
popup_list:
    path: /list/{page}/{category_service}/{country}
    defaults: { _controller: PopupBundle:Popup:popupList, page: 1 , category_service: 'none' , country: 'none'  }
    options:
        expose: true

popup_edit:
    path: /edit/{id}
    defaults: { _controller: PopupBundle:Popup:editPopup }

popup_delete:
    path: /delete/{id}
    defaults: { _controller: PopupBundle:Popup:deletePopup }

popup_new:
    path: /new
    defaults: { _controller: PopupBundle:Popup:newPopup }

###########################
#   APDO. AJAX   #
###########################
popup_get:
    path:  /get
    defaults: { _controller: PopupBundle:Popup:getPopup }
    options:
        expose: true
