############################
#   APDO. RUTAS PÚBLICAS   #
############################

login_ok:
    pattern:  /
    defaults: { _controller: UserBundle:Login:home }

##############################
#   APDO. RUTAS PARA LOGIN   #
##############################
   
profile:
    pattern:  /profile
    defaults: { _controller: UserBundle:Login:profile }
    
login:
    pattern:  /login
    defaults: { _controller: UserBundle:Login:login }

login_check:
    pattern:  /login_check
    defaults: { _controller: UserBundle:Login:login }
    
logout:
    pattern:  /logout
    
    