##############################
#   APDO. RUTAS PARA LOGIN   #
##############################
       
login:
    pattern:  /login
    defaults: { _controller: UserBundle:Login:login }

login_check:
    pattern:  /login_check
    defaults: { _controller: UserBundle:Login:login }
    
logout:
    pattern:  /logout
    
##############################
#   APDO. RUTAS USER         #
##############################
user_index:
    pattern: /index
    defaults: { _controller: UserBundle:Default:index }
    
user_profile:
    pattern: /profile
    defaults: { _controller: UserBundle:Default:profile }

user_list:
    pattern: /
    defaults: { _controller: UserBundle:Default:userList }

##############################
#       RUTAS AJAX           #
##############################
user_provinces: 
    pattern: /provincesFromRegion
    defaults: { _controller: UserBundle:Default:provincesFromRegion }