##############################
#   APDO. RUTAS PARA LOGIN   #
##############################
       
login:
    pattern:  /login
    defaults: { _controller: UserBundle:Login:login }

login_check:
    pattern:  /login_check
    defaults: { _controller: UserBundle:Login:login }
    
logout:
    pattern:  /logout
    
##############################
#   APDO. RUTAS USER         #
##############################
user_index:
    pattern: /index
    defaults: { _controller: UserBundle:Default:index }
    
user_profile:
    pattern: /profile
    defaults: { _controller: UserBundle:Default:profile }

user_list:
    pattern: /list
    defaults: { _controller: UserBundle:Default:userList }
    
user_edit:
    pattern: /edit/{id}
    defaults: { _controller: UserBundle:Default:editUser }

user_delete:
    pattern: /delete/{id}
    defaults: { _controller: UserBundle:Default:deleteUser }

user_new:
    pattern: /new
    defaults: { _controller: UserBundle:Default:newUser }

##############################
#       RUTAS AJAX           #
##############################
user_provinces: 
    pattern: /provincesFromRegion
    defaults: { _controller: UtilBundle:Default:provincesFromRegion }