##############################
#   APDO. RUTAS PARA LOGIN   #
##############################

_user_login:
    pattern:  /
    defaults: { _controller: UserBundle:Login:goToLogin }

user_login:
    pattern:  /login
    defaults: { _controller: UserBundle:Login:login }


user_login_check:
    pattern:  /login_check
    defaults: { _controller: UserBundle:Login:login }

user_logout:
    pattern:  /logout

##############################
#   APDO. RUTAS USER         #
##############################
user_index:
    pattern: /user/index
    defaults: { _controller: UserBundle:User:index }

user_profile:
    pattern: /user/profile
    defaults: { _controller: UserBundle:User:profile }

user_list:
    pattern: /user/list/{page}/{option}
    defaults: { _controller: UserBundle:User:userList, page: 1, option: null  }
    options:
        expose: true

user_edit:
    pattern: /user/edit/{id}
    defaults: { _controller: UserBundle:User:editUser }

user_delete:
    pattern: /user/delete/{id}
    defaults: { _controller: UserBundle:User:deleteUser }

user_new:
    pattern: /user/new/{type}
    defaults: { _controller: UserBundle:User:newUser }

user_select_new:
    pattern: /user/selectNewUser
    defaults: { _controller: UserBundle:User:selectNewUser }

generate_password:
    pattern: /user/changePassword/{id}
    defaults: { _controller: UserBundle:User:generatePassword }
    options:
        expose: true

change_password:
    pattern: /user/changePassword/{id}/{new_pass}/{rep_pass}/{old_pass}
    defaults: { _controller: UserBundle:User:changePassword, new_pass: 'none', rep_pass: 'none', old_pass: 'none' }
    options:
        expose: true

##############################
#       RUTAS AJAX           #
##############################
#user_provinces:
#    pattern: /provincesFromRegion
#    defaults: { _controller: UtilBundle:User:provincesFromRegion }