<?php
namespace Adservice\TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{
    public function findAllStatusDehydrated($indexedBy = 's.name')
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('s')
            ->from('TicketBundle:Status', 's', $indexedBy)
            ->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }
}