lock_list:
    pattern:  /lock/{lock}
    defaults: { _controller: LockBundle:lock:list, lock: null }

incidence:
    pattern:  /lock/{lock}
    defaults: { _controller: LockBundle:lock:list, lock: null }
