###########################
#   APDO. AJAX   #
###########################

editCar:
    path:  /car/edit/{id}
    defaults: { _controller: CarBundle:Car:editCar }
    
changeStatusCar:
    path: /car/changeStatus/{id}/{status}/{ticket_id}
    defaults: { _controller: CarBundle:Car:changeStatusCar }

# Car routes

car_list:
    path:  /car/list/{page}/{matricula}
    defaults: { _controller: CarBundle:Car:list, page: 1, matricula: null }
    options:
        expose: true
