###########################
#   APDO. AJAX   #
###########################

editCar:
    pattern:  /car/edit/{id_ticket}
    defaults: { _controller: CarBundle:Car:editCar }

car_model:
    pattern: /carModel/{id_brand}
    defaults: { _controller: CarBundle:Car:carModel }

car_version:
    pattern: /carVersion
    defaults: { _controller: CarBundle:Car:carVersion }