###########################
#   APDO. AJAX   #
###########################
car_model: 
    pattern: /carModel
    defaults: { _controller: CarBundle:Default:carModel }
    
car_version: 
    pattern: /carVersion
    defaults: { _controller: CarBundle:Default:carVersion }