<?php

namespace Adservice\UtilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function findDocumentFiltered($posts)
    {
        $em = $this->getEntityManager();

        $id_posts = array();
        foreach ($posts as $post){
            $id_posts[] = $post->getId();
        }

        $consulta = $em->createQuery('
            SELECT d FROM UtilBundle:Document d
            WHERE d.post in (:posts)
        ');

        $consulta->setParameter('posts', $id_posts);

	    $documents = $consulta->getResult();

        foreach ($documents as $doc)
        {
            $doc->setPath($doc->getImgPath());
        }
        return $documents;
    }
}