<?php
namespace Adservice\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Adservice\TicketBundle\Entity\TicketRepository;

/**
 * IncidenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidenceRepository extends EntityRepository
{
    public function findIncidencesFiltered($security, $request)
    {
        $em = $this->getEntityManager();

        //Inicializa variables
        $query = 'SELECT i FROM TicketBundle:Incidence i ';
        $joins = 'JOIN i.ticket t JOIN t.workshop w ';
        $where = 'WHERE i.id != 0 ';

        //Comprueba que los filtros no esten vacios y setea la variable para la consulta
        $consulta = TicketRepository::GetQuery($em, $security, $request, $query, $joins, $where);

   	    return $consulta->getResult();
    }
}