<?php
namespace Adservice\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
    public function findAllOpen($user, $status, $allTickets)
    {
        foreach ($allTickets as $ticket) {
            if($ticket->getStatus() == $status) {
                $tickets[] = $ticket;
            }
        }
        return $tickets;
    }

    // public function findAllAssigned ($user, $status, $bool)
    // {
    //     ($bool == 0) ? $assigned = $user->getId() : $assigned = null;

    //     $tickets = $this->findBy(array('status' => $status->getId(),
    //                                    'assigned_to' => $assigned));
    //     return $tickets;
    // }

/**
 * Encuentra los tickets segun el estado ($status) y los filtros que quieran devolver ($return)
 * @param  Entity $user     El usuario logeado actualmente
 * @param  Entity $status   El estado en que esta el ticket que se quiere devolver ('open', 'closed')
 * @param  Entity $return   El filtro de tickets que se quieran devolver ( 'all', 'accesible', 'answered', 'assigned')
 * @return array            array de tickets filtrados segun $status y $return
 */
    public function findAllTickets ($em, $user, $status, $return, $ordered=null)
    {
        $query = 'SELECT t FROM TicketBundle:Ticket t
                  WHERE t.status = '.$status->getId().'
                  ORDER BY t.modified_at '.$ordered;

        $consulta = $em->createQuery($query);

        $tickets = $consulta->getResult();

        $free_tickets           = array();  //array con los tickets pendientes de respuesta
        $assigned_tickets       = array();  //array con los tickets asignados al assessor
        $other_assessor_tickets = array();  //array con los tickets respondidos
        $answered_tickets       = array();  //array con los tickets asignados a otro assessor

        foreach ($tickets as $ticket) {

            // Se recoge el role del owner del ultimo post del ticket
            $posts = $ticket->getPosts();
            $last_post_owner_role_name = $posts[count($ticket->getPosts())-1]->getOwner()->getRoles()[0]->getName();

            // Si el ultimo post es de un user
            if ($last_post_owner_role_name == "ROLE_USER")
            {
                // Tickets no asignados a ningun assessor
                if ( $ticket->getAssignedTo() == null )
                {
                       $free_tickets[]  = $ticket;
                }
                else {
                    // Tickets asignados a el assessor
                    if($ticket->getAssignedTo() == $user) {
                        $assigned_tickets[] = $ticket;
                    }
                    // Tickets asignados a otro assessor
                    else {
                        $other_assessor_tickets[] = $ticket;
                    }
                }

            // Si el ultimo post es de un assessor
            }else {
                // Tickets asignados a el assessor
                if($ticket->getAssignedTo() == $user) {
                    $answered_tickets[] = $ticket;
                }
            }
        }

        //array con todos los tickets fitrados y ordenados (accesible, assigned, answered)
        // if ($return == 'all') {
        //     foreach ($accesible_tickets as $accesible) { $all_tickets[] = $accesible; }
        //     foreach ($assigned_tickets as $assigned)   { $all_tickets[] = $assigned;  }
        //     foreach ($answered_tickets as $answered)   { $all_tickets[] = $answered;  }
        //     return $all_tickets;
        // }
        // else {
            if ($return == 'free') {  return $free_tickets; } //array con los tickets pendientes de respuesta
            else {
                if ($return == 'assigned') { return $assigned_tickets; } //array con los tickets asignados al assessor
                else {
                    if($return == 'answered') { return $answered_tickets; } //array con los tickets respondidos
                    else {
                        if($return == 'other_assessor') { return $other_assessor_tickets; } //array con los tickets asignados a otro assessor
                    }
                }
            }
        // }
    }

    public function findAllByOwner ($user, $status)
    {
        $tickets = $this->findBy(array('owner' => $user->getId(),
                                       'status' => $status->getId()));
        return $tickets;
    }

    public function findAllByWorkshop ($user, $status)
    {
        $tickets = $this->findBy(array('workshop' => $user->getWorkshop()->getId(),
                                       'status' => $status->getId()));
        return $tickets;
    }

    public function findTicketsFiltered($security, $request)
    {
        $em     = $this->getEntityManager();

        //Inicializa variables
        $query  = 'SELECT t FROM TicketBundle:Ticket t ';
        $joins  = 'JOIN t.workshop w ';
        $where  = 'WHERE t.status = :status ';

        //Comprueba que los filtros no esten vacios y setea la variable para la consulta
        $consulta = $this->GetQuery($em, $security, $request, $query, $joins, $where);

        return $consulta->getResult();
    }

    public function findTickets($security)
    {
        $em = $this->getEntityManager();

        if ($security->isGranted('ROLE_ASSESSOR'))
        {
            $consulta = $em->createQuery('
                SELECT t FROM TicketBundle:Ticket t
                WHERE t.status = :status
            ');

        }else{

            $consulta = $em->createQuery('
                SELECT t FROM TicketBundle:Ticket t
                WHERE t.status = :status
                AND t.workshop = :workshop
            ');

            $consulta->setParameter('workshop', $security->getToken()->getUser()->getWorkshop());
        }

        $consulta->setParameter('status', 0);

	    return $consulta->getResult();
    }

    public static function GetQuery($em, $security, $request, $query, $joins, $where)
    {
        $params = array();

        //Filtro para tickets abiertos
        $open   = $em->getRepository('TicketBundle:Status')->findOneBy(array('name' => 'open'));
        $params[] = array('status', $open);

        //Filtros enviados
        $id_ticket   = $request->get('id_ticket');

        if ($id_ticket != "")
        {
            $where .= 'AND t.id = :id_ticket ';
            $params[] = array('id_ticket', $id_ticket);
        }

        if ($security->isGranted("ROLE_ASSESSOR")) {

            //Filtros enviados de assessor
            $id_partner  = $request->get('id_partner');
            $id_workshop = $request->get('id_workshop');
            $id_region   = $request->get('id_region');

            if ($id_partner != "0") {

                $joins .= 'JOIN w.partner p ';
                $where .= 'AND p.id = :id_partner ';
                $params[] = array('id_partner', $id_partner);
            }

            if ($id_workshop != "")
            {
                $where .= 'AND w.id = :id_workshop ';
                $params[] = array('id_workshop', $id_workshop);
            }

            if ($id_region != "0") {

                $joins .= 'JOIN w.region r ';
                $where .= 'AND r.id = :id_region ';
                $params[] = array('id_region', $id_region);
            }
        }else{
            //Filtros enviados de user
            $id_workshop = $security->getToken()->getUser()->getWorkshop()->getId();

            $where .= 'AND w.id = :id_workshop ';
            $params[] = array('id_workshop', $id_workshop);
        }

        //Crea la consulta
        $consulta = $em->createQuery($query.$joins.$where.'ORDER BY t.id ');

        //hace un recorrido de $params para extraer los parametros de la consulta
        foreach($params as $param){
            $consulta->setParameter($param[0], $param[1]);
        }

        return $consulta;
    }
}
