<?php
namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkshopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopRepository extends EntityRepository
{
    /**
     * Devuelve el ultimo ID almacenado en DB
     * @return integer
     */
    public function getLastId()
    {
        $em = $this->getEntityManager();

        $query = 'SELECT MAX(w) FROM AppBundle:Workshop w';
        $consulta = $em->createQuery($query);

        $id = $consulta->getSingleResult()[1];

        return (int)$id;
    }

    /**
     * Devuelve el ultimo ID almacenado en DB
     * @return integer
     */
    public function getMaxIdByCodePartner($code_partner)
    {
        $em = $this->getEntityManager();

        $query = 'SELECT MAX(w.code_workshop) FROM AppBundle:Workshop w Where w.code_partner = '.$code_partner;
        $consulta = $em->createQuery($query);

        $id = $consulta->getSingleResult()[1];

        return (int)$id;
    }

    public function findPhone($number) {
        $em = $this->getEntityManager();
        $query = 'SELECT COUNT(w) FROM AppBundle:Workshop w '
            .'WHERE w.phone_number_1 = '.$number
            .'OR w.phone_number_2 = '.$number
            .'OR w.mobile_number_1 = '.$number
            .'OR w.mobile_number_1 = '.$number
            .'OR w.fax = '.$number;
        $consulta = $em-> createQuery($query);

        return $consulta->getResult()[0];

    }

    public function findPhoneGetCode($number) {

        $em = $this->getEntityManager();
        $query = 'SELECT w.code_partner, w.code_workshop, w.name FROM AppBundle:Workshop w '
            .'WHERE w.phone_number_1 = '.$number
            .'OR w.phone_number_2 = '.$number
            .'OR w.mobile_number_1 = '.$number
            .'OR w.mobile_number_1 = '.$number;
        $consulta = $em-> createQuery($query);

        $result = $consulta->getResult()[0];
        $res = $result['code_partner'].' - '.$result['code_workshop'].' '.$result['name'];

        return $res;
    }

    public function findPhoneNoId($number,$id) {
        $em = $this->getEntityManager();
        $query = 'SELECT COUNT(w) FROM AppBundle:Workshop w '
            .'WHERE w.id != '.$id.' AND (w.phone_number_1 = '.$number
            .' OR w.phone_number_2 = '.$number
            .' OR w.mobile_number_1 = '.$number
            .' OR w.mobile_number_1 = '.$number.')';
        $consulta = $em-> createQuery($query);
        return $consulta->getResult()[0];
    }

    public function findPhoneNoIdGetCode($number,$id) {
        $em = $this->getEntityManager();
        $query = 'SELECT w.code_partner, w.code_workshop, w.name FROM AppBundle:Workshop w '
            .'WHERE w.id != '.$id.' AND (w.phone_number_1 = '.$number
            .' OR w.phone_number_2 = '.$number
            .' OR w.mobile_number_1 = '.$number
            .' OR w.mobile_number_1 = '.$number.')';
        $consulta = $em-> createQuery($query);

        $result = $consulta->getResult()[0];
        $res = $result['code_partner'].' - '.$result['code_workshop'].' '.$result['name'];

        return $res;

    }

}
