parameters:
#    util.example.class: Adservice\UtilBundle\Example

services:
    default.language:
        class: Adservice\UtilBundle\Controller\ServiceController
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setDefaultLanguage }

    isMSIE:
        class: Adservice\UtilBundle\Controller\ServiceController

    cms.mailer:
        class: Adservice\UtilBundle\Entity\Mailer
        arguments: ["@mailer","@swiftmailer.transport.real","@templating"]
        
    instant_mailer:
        class: %swiftmailer.class%
        arguments: ["@?swiftmailer.transport.real"]
        
    util_controller:
        class: Adservice\UtilBundle\Controller\UtilController
        scope: request
        strict: false
        public: true
        arguments: ["@request", "@doctrine.orm.entity_manager", "@security.token_storage"]

    security:
        class: Adservice\UtilBundle\Services\Security
        arguments: ["%secret_iv%"]

    dgt_webservice:
        class: Adservice\UtilBundle\Services\DGTWebservice
        arguments: ["@security", "@doctrine.orm.entity_manager", "@security.token_storage"]

#    my.listener:
#        class: Adservice\UtilBundle\Listener\EntityUtilListener
#        arguments: ['@service_container']
##        arguments: ["@security.context"]
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
