parameters:
#    util.example.class: Adservice\UtilBundle\Example

services:
    default.language:
        class: Adservice\UtilBundle\Controller\ServiceController
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setDefaultLanguage }

    isMSIE:
        class: Adservice\UtilBundle\Controller\ServiceController

    cms.mailer:
        class: Adservice\UtilBundle\Entity\Mailer
        arguments: ["@mailer","@swiftmailer.transport.real","@templating"]

    instant_mailer:
        class: %swiftmailer.class%
        arguments: ["@?swiftmailer.transport.real"]

#    my.listener:
#        class: Adservice\UtilBundle\Listener\EntityUtilListener
#        arguments: ['@service_container']
##        arguments: ["@security.context"]
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
