
Adservice\UtilBundle\Entity\Document:
    properties:
        file:
            - File:
                maxSize: 4096k
                mimeTypes: [application/pdf, application/x-pdf, image/bmp, image/jpeg, image/png, image/gif, application/mspowerpoint]
                mimeTypesMessage: 'Please upload a valid file (image or pdf)'