<?php
namespace Adservice\WorkshopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiagnosisMachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosisMachineRepository extends EntityRepository
{
    public static function findDiagnosisMachinesList($em, $country=null)
    {
        $query = 'SELECT t ';
        $from  = 'FROM WorkshopBundle:DiagnosisMachine t ';
        $where = 'WHERE t.active = 1 ';
        if($country != null) $where = $where.' AND t.country = '.$country.' ';

        //Crea la consulta
        // echo $query.$where.' ORDER BY w.id ';die;
        $consulta = $em->createQuery($query.$from.$where.' ORDER BY t.name ');
        $array = $consulta->getResult();

        //Si la consulta da resultado y hay algun campo de los filtros introducido se devuelve el resultado, sino se devuelve un array vacio
        if (count($array) > 0)
            {  return $array;  }
        else
            {  return array('0' => new DiagnosisMachine()); }
    }
}
